- defaults:
    link:
        create: true
        relink: true

- clean: []

- link:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.tmux.conf:
    ~/.zsh:
    ~/.zshrc:

- shell: []
