- defaults:
    link:
        create: true
        relink: true

- create:
    '~/.ssh':
        mode: 0700

- clean: ['~', '~/.config']

- link:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ''
    ~/.emacs.d:
    ~/.emacs:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.shell:
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc:
    ~/.vscode-server/data/Machine/settings.json:
      if: '[ `uname` = Linux ]'
      create: true
      path: vscode/linux/settings.json
    ~/.zsh:
    ~/.zshrc:

- shell:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - >
      git clean -f
      emacs.d/vendor/
      vim/pack/vendor/start/
